name: Delete Branch Option for Non-Matching Branches

on:
  pull_request:
    types: [closed]

jobs:
  check-branch-name:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name pattern
        id: check-branch
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" =~ ^TD[0-9]+-[0-9]+R[0-9]+ ]]; then
            echo "::set-output name=delete_branch::false"
          else
            echo "::set-output name=delete_branch::true"
          fi
          
      - name: Delete branch if not matching pattern
        if: steps.check-branch.outputs.delete_branch == 'true'
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branches: ${{ github.event.pull_request.head.ref }}
